REPLACE
NO UPDATE
ONLC
(OSMAN:27)OPR.MAI,(OSMAN:31)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:34)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:35)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:37)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:54)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:56)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:65)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:55)OPR.MAI
(OSMAN:27)OPR.MAI,(OSMAN:57)OPR.MAI
QUIT
